AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Zit AI Mentor Backend - AI-powered Git assistant

Globals:
  Function:
    Timeout: 60
    MemorySize: 512
    Runtime: python3.12
    Tracing: Active

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
  BedrockModelId:
    Type: String
    Default: anthropic.claude-3-sonnet-20240229-v1:0

Resources:
  ZitAIMentorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub zit-ai-mentor-${Environment}
      CodeUri: ../lambda/
      Handler: handler.lambda_handler
      Environment:
        Variables:
          BEDROCK_MODEL_ID: !Ref BedrockModelId
          ENVIRONMENT: !Ref Environment
          LOG_LEVEL: INFO
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
                - bedrock:InvokeModelWithResponseStream
              Resource: !Sub 'arn:aws:bedrock:${AWS::Region}::foundation-model/${BedrockModelId}'
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*'
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /mentor
            Method: POST
            RestApiId: !Ref ZitApi
        HealthCheck:
          Type: Api
          Properties:
            Path: /health
            Method: GET
            RestApiId: !Ref ZitApi

  ZitApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub zit-api-${Environment}
      StageName: !Ref Environment
      Cors:
        AllowOrigin: "'*'"
        AllowHeaders: "'Content-Type,Authorization,x-api-key'"
        AllowMethods: "'GET,POST,OPTIONS'"
      Auth:
        ApiKeyRequired: true
        UsagePlan:
          CreateUsagePlan: SHARED
          UsagePlanName: !Sub zit-usage-plan-${Environment}
          Description: Usage plan for Zit AI Mentor API
          Quota:
            Limit: 5000
            Period: MONTH
          Throttle:
            BurstLimit: 20
            RateLimit: 10

  # CloudWatch Alarms
  LambdaErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub zit-ai-mentor-errors-${Environment}
      AlarmDescription: Triggers when the Lambda function error rate exceeds threshold
      Namespace: AWS/Lambda
      MetricName: Errors
      Dimensions:
        - Name: FunctionName
          Value: !Ref ZitAIMentorFunction
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 2
      Threshold: 5
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching

  LambdaLatencyAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub zit-ai-mentor-latency-${Environment}
      AlarmDescription: Triggers when p90 Lambda duration exceeds 30 seconds
      Namespace: AWS/Lambda
      MetricName: Duration
      Dimensions:
        - Name: FunctionName
          Value: !Ref ZitAIMentorFunction
      ExtendedStatistic: p90
      Period: 300
      EvaluationPeriods: 2
      Threshold: 30000
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching

  LambdaThrottleAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub zit-ai-mentor-throttles-${Environment}
      AlarmDescription: Triggers when Lambda invocations are throttled
      Namespace: AWS/Lambda
      MetricName: Throttles
      Dimensions:
        - Name: FunctionName
          Value: !Ref ZitAIMentorFunction
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching

  Api5xxAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub zit-api-5xx-${Environment}
      AlarmDescription: Triggers when API Gateway returns 5xx errors
      Namespace: AWS/ApiGateway
      MetricName: 5XXError
      Dimensions:
        - Name: ApiName
          Value: !Sub zit-api-${Environment}
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 2
      Threshold: 5
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub https://${ZitApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/mentor
    Export:
      Name: !Sub ${AWS::StackName}-ApiEndpoint
  
  HealthEndpoint:
    Description: Health check endpoint
    Value: !Sub https://${ZitApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/health
  
  FunctionArn:
    Description: Lambda Function ARN
    Value: !GetAtt ZitAIMentorFunction.Arn
    Export:
      Name: !Sub ${AWS::StackName}-FunctionArn
  
  FunctionName:
    Description: Lambda Function Name
    Value: !Ref ZitAIMentorFunction

  ApiKeyId:
    Description: Retrieve your API key with this CLI command
    Value: !Sub 'aws apigateway get-api-keys --name-query zit-usage-plan-${Environment} --include-values --query items[0].value --output text --region ${AWS::Region}'
